###
GET http://localhost:3000/recados
###
POST http://localhost:3000/recados
Content-Type: application/json

{
    "recado": "Este é outro recado diferente",
    "nova chave": "outro valor"
}

###
PATCH http://localhost:3000/recados/1
Content-Type: application/json

{
    "recado": "Este é outro recado atualizado"
}

###

DELETE http://localhost:3000/recados/1